[package]
name = "movie"
version = "0.1.0"
authors = ["Paweł Zmarzły <pawo2500@gmail.com>"]
edition = "2018"

[dependencies]
"movie_utils" = { path = "../movie_utils" }
"movie_derive" = { path = "../movie_derive" }
